# -*- coding: utf-8 -*-
"""Data Segmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ZE9AECkfJL26jc0qgNR_JjxtvbB0UWC
"""

!pip install keras

from google.colab import drive
drive.mount('/content/gdrive')

import pandas as pd

from keras.preprocessing import image

import matplotlib.pyplot as plt

img_path="gdrive/My Drive/upl.jpg"

img=image.load_img(img_path,target_size=(400,400))
img=image.img_to_array(img)
img=img/255.0

plt.imshow(img)
plt.axis("off")
plt.show()

print(type(img))

from keras.preprocessing.image import ImageDataGenerator

datagen=ImageDataGenerator(
              rotation_range=30,
              width_shift_range=0.2,
              height_shift_range=0.3
             ,shear_range=0.2,
              zoom_range=0.2,
              horizontal_flip=0.2,
              fill_mode="nearest"
 )

input_batch=img.reshape((1,*img.shape))

print(input_batch.shape)

print(input_batch)

i=0


for batch in datagen.flow(input_batch,batch_size=1):
  plt.figure()
  plt.imshow(image.img_to_array(batch[0]))
  i+=1
  plt.axis("off")
  plt.show()
  if(i==10):
    break

